## Default config file for RouletteRemake

##  _____  _             _       _____                      _             
## |  __ \| |           (_)     |  __ \                    | |            
## | |__) | |_   _  __ _ _ _ __ | |__) |___ _ __ ___   __ _| | _____  ___ 
## |  ___/| | | | |/ _` | | '_ \|  _  // _ \ '_ ` _ \ / _` | |/ / _ \/ __|
## | |    | | |_| | (_| | | | | | | \ \  __/ | | | | | (_| |   <  __/\__ \
## |_|    |_|\__,_|\__, |_|_| |_|_|  \_\___|_| |_| |_|\__,_|_|\_\___||___/
##                  __/ |                                                 
##                 |___/         


## How many chambers are in the gun? You can have up to 2-5 chambers.
Chambers: 5
## There will be more chambers available in future updates.
